# (1) 빌드
# FROM node:18.12.1 as builder

# RUN mkdir /app
# WORKDIR /app

# COPY package.json .
# RUN yarn install 

# COPY . .
# RUN yarn buildcla

# (2) Node 실행
FROM node:18.16.0-alpine

RUN mkdir /app
WORKDIR /app
COPY ./.output /app/.output

ENV NODE_TLS_REJECT_UNAUTHORIZED=0
ENV NODE_ENV=prod

CMD ["node", "/app/.output/server/index.mjs" ]