name: Docent Front CI/CD

on:
    pull_request:
        types: [closed]
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Docker Build And Push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: docker/Dockerfile
                  platforms: linux/amd64
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/Docent-front

            - name: Deploy
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  port: ${{ secrets.SSH_PORT }}
                  username: root
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      docker pull ${{ secrets.DOCKER_USERNAME }}/Docent-front
                      docker stop $(docker ps -a -q)
                      docker run -d --log-driver=syslog -p 80:80 ${{ secrets.DOCKER_USERNAME }}/Docent-front
                      docker rm $(docker ps --filter 'status=exited' -a -q)
