name: docent

on:
    push:
        branches: [develop]
#   pull_request:
#     branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v2
            - name: Docker build
              run: |
                  docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
                  docker build -f ./docker/Dockerfile -t taewan2002/docent-front .
                  docker push taewan2002/docent-front

            - name: Deploy
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.NCP_HOST }}
                  username: ${{ secrets.NCP_USER }}
                  password: ${{ secrets.NCP_PASSWORD }}
                  key: ${{ secrets.NCP_KEY }}
                  envs: GITHUB_SHA
                  script: |
                      # Pull the new image
                      sudo docker pull taewan2002/docent-front

                      # Stop & Start
                      echo "✔️ Docker Stop & Start"
                      sudo docker stop docent-front
                      sudo docker run -d --name docent-front -p 3000:3000 taewan2002/docent-front

                      # Check
                      echo "✔️ Docker ps"
                      docker ps

                      # Cleanup old images
                      echo "🧹 Cleaning up old Docker images"
                      sudo docker rmi -f $(sudo docker images -q) || true
