name: docent-front

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v2
            - name: Add remote host key
              run: ssh-keyscan -H ${{ secrets.NCP_HOST }} >> ~/.ssh/known_hosts

            - name: Copy File
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.NCP_HOST }}
                  username: ${{ secrets.NCP_USER }}
                  password: ${{ secrets.NCP_PASSWORD }}
                  key: ${{ secrets.NCP_KEY }}
                  envs: GITHUB_SHA
                  script: |
                      # SSH key를 ssh-agent에 추가
                      eval "$(ssh-agent -s)"
                      echo "${{ secrets.NCP_KEY }}" | ssh-add -

                      # 파일을 원격 서버에 복사
                      rm -rf Docent-Front
                      mkdir Docent-Front
                      scp -r . ${{ secrets.NCP_USER }}@${{ secrets.NCP_HOST }}:/Docent-Front

                  #   # 도커 빌드
                  #   cd Docent-Front
                  #   docker build -f docker/Dockerfile -t docent-front  .

                  #     docker stop $(docker ps -a -q)
                  #     docker run -p 80:80 --name docent-front -v /etc/letsencrypt/live/:/etc/letsencrypt/live/ taewan2002/docent-front
                  #     docker rm $(docker ps --filter 'status=exited' -a -q)
