name: docent-front

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v2

            - name: Prune directory 'Docent-Front'
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.NCP_HOST }}
                  username: ${{ secrets.NCP_USER }}
                  password: ${{ secrets.NCP_PASSWORD }}
                  key: ${{ secrets.NCP_KEY }}
                  script: |
                      rm -rf Docent-Front
                      mkdir Docent-Front

                  #   # 도커 빌드
                  #   cd Docent-Front
                  #   docker build -f docker/Dockerfile -t docent-front  .

                  #     docker stop $(docker ps -a -q)
                  #     docker run -p 80:80 --name docent-front -v /etc/letsencrypt/live/:/etc/letsencrypt/live/ taewan2002/docent-front
                  #     docker rm $(docker ps --filter 'status=exited' -a -q)

            - name: Copy all
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.NCP_HOST }}
                  username: ${{ secrets.NCP_USER }}
                  key: ${{ secrets.NCP_KEY }}
                  password: ${{ secrets.NCP_PASSWORD }}
                  port: 22
                  source: "./"
                  target: "/Docent-Front"

            # - name: Docker build and run
            #   uses: appleboy/ssh-action@master
            #   with:
            #       host: ${{ secrets.NCP_HOST }}
            #       username: ${{ secrets.NCP_USER }}
            #       password: ${{ secrets.NCP_PASSWORD }}
            #       key: ${{ secrets.NCP_KEY }}
            #       script: |
            #           cd /Docent-Front
            #           docker build -f docker/Dockerfile -t docent-front .
            #           docker-compose -f docker/docker-compose.yml down
            #           docker-compose -f docker/docker-compose.yml up
