name: docent-front

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v2

            - name: Prune directory 'Docent-Front'
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.NCP_HOST }}
                  username: ${{ secrets.NCP_USER }}
                  password: ${{ secrets.NCP_PASSWORD }}
                  key: ${{ secrets.NCP_KEY }}
                  script: |
                      rm -rf /Docent-Front/.output
                      mkdir /Docent-Front/.output

            - name: Copy all
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.NCP_HOST }}
                  username: ${{ secrets.NCP_USER }}
                  key: ${{ secrets.NCP_KEY }}
                  password: ${{ secrets.NCP_PASSWORD }}
                  port: 22
                  source: "./.output"
                  target: "/Docent-Front/.output"
